import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthInitializer from "@/components/globalfiles/setupfiles/authInitializer";
import NavigationBar from "@/components/globalfiles/uifiles/Navbar";
import StoreProvider from "@/components/globalfiles/setupfiles/storeprovider";
import Snackbar from "@/components/globalfiles/uifiles/Snackbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <AuthInitializer />
          <NavigationBar/>
          {children}
           <Snackbar />
        </StoreProvider>
      </body>
    </html>
  );
}
